export const GET_RECIPES = "GET_RECIPES";
export const GET_DETAILRECIPE = "GET_DETAILRECIPE";
export const GET_DIETS = "GET_DIETS";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const GET_RECIPESBYNAME = "GET_RECIPESBYNAME";
